### ISSUE TITLE
jscolor [suggest]

### ISSUE THREAD

**Issue by jonlepage** [pixijs/pixi-text-style#13]
a little more intuitive suggestion to work with colors.
http://jscolor.com/examples/
The native color windows box are hard to work. :)

**Comment by bigtimebuddy** [comment]
I agree that the native color window boxes are annoying. This is a good suggestion, I'll see what I can do.

**Comment by jonlepage** [comment]
@bigtimebuddy 
if you are also interested.
since you are already using boostrape libs.
using slider can be also nice , maybe?
http://seiyria.com/bootstrap-slider/
provided you find the right limit (range) for each.

**Comment by bigtimebuddy** [comment]
The problem is getting it to play well with the React-like framework I’m using since it’s not jquery. It’s mostlynusing bootstrap from the css styles

**Comment by jonlepage** [comment]
if you want use jscolor
it not explain in guide, but for your listener it will be.
hope this can save your time :)

```javascript
        // listener when color change
        obj.onFineChange = function(){
            refreshYourHtml();
        };
```

**Comment by jonlepage** [comment]
i also don't use jquery on my side. (i know nothing about React!)
Only bootstrap

```javascript
         //attache a new input color module to html tint
        const jsColor = new jscolor(document.getElementById(!light&&"tint"||"color"));
            jsColor.keyName = !light&&"tint"||"color";
            jsColor.zIndex = 9999999;
        Cage_DataEditor.jsColor = jsColor;
```

![upload_2018-3-23_6-31-5](https://user-images.githubusercontent.com/24865815/41069477-0d93928a-69bc-11e8-9b59-fa3eb3709e00.png)
![upload_2018-3-23_16-33-48](https://user-images.githubusercontent.com/24865815/41069479-10de5f06-69bc-11e8-85be-5d90bb94ed5e.png)
![3ugylbop_o](https://user-images.githubusercontent.com/24865815/41069482-1331232e-69bc-11e8-91df-3f34e531bde2.png)
![bnwlqtzg_o](https://user-images.githubusercontent.com/24865815/41069484-15b8462c-69bc-11e8-8d47-2a059080f93b.png)

also little example for html code , i dont know if this will help you.
this it example of the fallOff slider from pixi-light with bootstrape

```html
                <tr><!--falloff -->
                    <td>
                        <div class="funkyradio funkyradio-success">
                            <input type="checkbox" name="checkbox" id="_falloff"/>
                            <label for="_falloff" style="text-indent:0px;margin-right:0px;">.</label>
                        </div>
                    </td>
                    <td>[0.75,3,20]</td>
                    <td id="_setDark-BoxDisplay" style="display: block;">
                        <font color="#d2bc97">falloff attenuation coefficients controler</font><br><br>
                        <div class="form-control">
                            <b>kc</b> <input value=0.75 data-slider-min=0.01 data-slider-max=2 data-slider-step=0.01 data-slider-value=0.75 data-slider-id="RC" id="kc" data-slider-handle="triangle" type="text" class="span2"  /><br>
                            <b>kl</b> <input value=3 data-slider-min=0.01 data-slider-max=20 data-slider-step=0.01 data-slider-value=3 data-slider-id="GC" id="kl" data-slider-handle="triangle" type="text" class="span2"/><br>
                            <b>kq</b> <input value=20 data-slider-min=0.01 data-slider-max=50 data-slider-step=0.01 data-slider-value=20 data-slider-id="BC" id="kq" data-slider-handle="triangle" type="text" class="span2"/>
                        </div> 
                    </td>
```
and css, please dont punish me lol, i know i use transition css
```css
#RGB {
	height: 20px;
  background: rgb(128, 128, 128);
}
#RC .slider-selection {
  background: #FF8282;
  border: 1px solid rgb(32, 32, 32);
  transition: all 1s; /* transition when the mouse over */
}
#RC .slider-handle {
	background: red;
}
#GC .slider-selection {
  background: #428041;
  border: 1px solid rgb(32, 32, 32);
  transition: all 1s; /* transition when the mouse over */
}
#GC .slider-handle {
	background: green;
}
#BC .slider-selection {
  background: #8283FF;
  border: 1px solid rgb(32, 32, 32);
  transition: all 1s; /* transition when the mouse over */
}
#BC .slider-handle {
  border-bottom-color: blue;
}
#R, #G, #B {
	width: 300px;
}
#BC {
	transition: all 1s; /* transition when the mouse over */
}
#GC {
	transition: all 1s; /* transition when the mouse over */
}
#RC {
	transition: all 1s; /* transition when the mouse over */
}
#BC:hover { 
  border: 2px solid #8283FF;
  border-radius: 50%;
}
#GC:hover { 
  border: 2px solid #428041;
  border-radius: 50%;
}
#RC:hover { 
  border: 2px solid #FF8282;
  border-radius: 50%;
}
```

for bootstrap button i also use a another hack
they are superfluous code for design 
https://bootsnipp.com/snippets/featured/funky-radio-buttons
